language: php

php:
    - 5.5
    - 5.6

before_install:
    - pecl install v8js
    - composer self-update

install:
    - COMPOSER_ROOT_VERSION=0.4.1 travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
    - composer info -i

script:
    - ./vendor/bin/phpunit


