language: php

php:
    - 5.5
    - 5.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libv8-dev
    - printf "\n" | pecl install v8js
    - composer self-update --quiet --no-interaction

install:
    - COMPOSER_ROOT_VERSION=dev-master travis_retry composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpunit


